version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: creative
      POSTGRES_USER: creative
      POSTGRES_PASSWORD: creative
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-02-17T01-25-47Z
    command: server /data --console-address :9001
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile.backend
    command: uv run uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ../config/env/.env.local.example
    volumes:
      - ..:/workspace
    depends_on:
      - postgres
      - minio
      - redis
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile.frontend
    command: pnpm dev --host 0.0.0.0
    env_file:
      - ../config/env/.env.local.example
    volumes:
      - ..:/workspace
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres-data:
  minio-data:
